version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1.5-browsers
    working_directory: ~/testneem
    steps:
       - checkout
       - run:
            name: Install awscli
            command: sudo apt-get update && sudo apt-get install -y awscli
       - run:
            name: configure configure
            command: aws configure set default.s3.signature_version s3v4
       - run:
           name: Deploy to S3
           command: aws deploy push \
                    --application-name first-auto-deployment \
                    --description "This is a revision for the application first-auto-deployment" \
                    --ignore-hidden-files \
                    --s3-location s3://testdeploycode/testdeploy.zip \
                    --source .
    deploy:
       machine:
        enabled: true
        staging:
        branch: master
        codedeploy:
          first-auto-deployment:
        deployment_group: first-auto-deployment
    workflows:
      version: 2
      build-and-deploy:
        jobs:
          - build
          - deploy:
              requires:
                - build
