version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1.5-browsers

    working_directory: ~/neemchand/testneem
    steps:
       - run:
            name: Install awscli
            command: sudo apt-get update && sudo apt-get install -y awscli
       - run:
            name: configure configure
            command: aws configure set default.s3.signature_version s3v4
    workflows:
    version: 2
    test:
      jobs:
       - build
    deployment:
      prod:
      branch: master
       commands:
       - aws s3 sync . s3://neem-test-bucket/codedeploy --region ap-south-1 --delete

