version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1.5-browsers
    working_directory: ~/testneem
    steps:
       - checkout
       - run:
            name: Install awscli
            command: sudo apt-get update && sudo apt-get install -y awscli
       - run:
            name: configure configure
            command: aws configure set default.s3.signature_version s3v4
       - run:
           name: Deploy to S3
           command: aws s3 sync . s3://testdeploycode --region ap-south-1 --delete
    deploy:
       machine:
       enabled: true
        staging:
        branch: master
        codedeploy:
          code_deployment_app:
        deployment_group: staging
    workflows:
      version: 2
      build-and-deploy:
        jobs:
          - build
          - deploy:
              requires:
                - build
